package lbm.boundary;

public enum BoundaryDirection {
    NONE,
    NORTH,
    EAST,
    SOUTH,
    WEST,
    NORTHEAST_CONCAVE,
    NORTHWEST_CONCAVE,
    SOUTHWEST_CONCAVE,
    SOUTHEAST_CONCAVE,
    NORTHEAST_CONVEX,
    NORTHWEST_CONVEX,
    SOUTHEAST_CONVEX,
    SOUTHWEST_CONVEX,
    NORTH_CORNER,
    SOUTH_CORNER,
    WEST_CORNER,
    EAST_CORNER
}

